name: Azure Blob CD

on:
  push:
    branches:
      - master

jobs:
  CreateZip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - run: mkdir vendor-zip
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./vendor-zip/vendor.zip ./
      - uses: actions/upload-artifact@master
        with:
          name: vendor
          path: vendor-zip
  UploadToAzureStorage:
    needs: CreateZip
    runs-on: windows-latest
    env:
      Configuration: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0

    # *****************  UPLOAD TO AZURE BLOB (for SideLoad package's AppInstaller) ************************ #

    # This is my custom GitHub Action, available in the GitHub Marketplace for anyone to use :)
      - name: Uploading to Azure Blob
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.4
        with:
          connection_string: ${{ secrets.AZURE_DVLUP_BLOB_CONNECTION_STRING }}
          container_name: files
          source_folder: src\
          destination_folder: sp_Develop
          clean_destination_folder: true
